// Shared curated sample arc, 2010 -> present.
// Counts grow each year (2 -> ~13) so the timeline shows the "few big statements ->
// dense constellation" transition. Real albums so Deezer returns real cover art.
// Replace this whole list with Corey's actual listening history later.
// Shape: [artist, album, representative song, year, genre]
export const CURATED = [
  // 2010 — 2, the doorway
  ['Kanye West', 'My Beautiful Dark Twisted Fantasy', 'Runaway', 2010, 'hip-hop'],
  ['Arcade Fire', 'The Suburbs', 'The Suburbs', 2010, 'indie'],
  // 2011 — 3
  ['Bon Iver', 'Bon Iver, Bon Iver', 'Holocene', 2011, 'folk'],
  ['M83', 'Hurry Up, We’re Dreaming', 'Midnight City', 2011, 'electronic'],
  ['The Weeknd', 'House of Balloons', 'Wicked Games', 2011, 'r&b'],
  // 2012 — 4
  ['Frank Ocean', 'Channel Orange', 'Thinkin Bout You', 2012, 'r&b'],
  ['Kendrick Lamar', 'good kid, m.A.A.d city', 'Money Trees', 2012, 'hip-hop'],
  ['Tame Impala', 'Lonerism', 'Feels Like We Only Go Backwards', 2012, 'indie'],
  ['Grimes', 'Visions', 'Oblivion', 2012, 'pop'],
  // 2013 — 5
  ['Daft Punk', 'Random Access Memories', 'Get Lucky', 2013, 'electronic'],
  ['Vampire Weekend', 'Modern Vampires of the City', 'Step', 2013, 'indie'],
  ['Disclosure', 'Settle', 'Latch', 2013, 'electronic'],
  ['Chance the Rapper', 'Acid Rap', 'Cocoa Butter Kisses', 2013, 'hip-hop'],
  ['Kanye West', 'Yeezus', 'Bound 2', 2013, 'hip-hop'],
  // 2014 — 6
  ['FKA twigs', 'LP1', 'Two Weeks', 2014, 'r&b'],
  ['Flying Lotus', 'You’re Dead!', 'Never Catch Me', 2014, 'electronic'],
  ['Run the Jewels', 'Run the Jewels 2', 'Close Your Eyes', 2014, 'hip-hop'],
  ['Alvvays', 'Alvvays', 'Archie, Marry Me', 2014, 'indie'],
  ['Mac DeMarco', 'Salad Days', 'Chamber of Reflection', 2014, 'indie'],
  ['Caribou', 'Our Love', 'Can’t Do Without You', 2014, 'electronic'],
  // 2015 — 7
  ['Kendrick Lamar', 'To Pimp a Butterfly', 'Alright', 2015, 'hip-hop'],
  ['Tame Impala', 'Currents', 'Let It Happen', 2015, 'indie'],
  ['Sufjan Stevens', 'Carrie & Lowell', 'Should Have Known Better', 2015, 'folk'],
  ['Jamie xx', 'In Colour', 'Gosh', 2015, 'electronic'],
  ['Grimes', 'Art Angels', 'Kill V. Maim', 2015, 'pop'],
  ['Kamasi Washington', 'The Epic', 'Change of the Guard', 2015, 'jazz'],
  ['Courtney Barnett', 'Sometimes I Sit and Think, and Sometimes I Just Sit', 'Pedestrian at Best', 2015, 'rock'],
  // 2016 — 8
  ['Frank Ocean', 'Blonde', 'Nights', 2016, 'r&b'],
  ['A Tribe Called Quest', 'We got it from Here... Thank You 4 Your service', 'We the People....', 2016, 'hip-hop'],
  ['Radiohead', 'A Moon Shaped Pool', 'Daydreaming', 2016, 'rock'],
  ['Solange', 'A Seat at the Table', 'Cranes in the Sky', 2016, 'r&b'],
  ['Bon Iver', '22, A Million', '33 “GOD”', 2016, 'folk'],
  ['Nicolas Jaar', 'Sirens', 'No', 2016, 'electronic'],
  ['Anderson .Paak', 'Malibu', 'Come Down', 2016, 'r&b'],
  ['David Bowie', 'Blackstar', 'Lazarus', 2016, 'rock'],
  // 2017 — 9
  ['Kendrick Lamar', 'DAMN.', 'DNA.', 2017, 'hip-hop'],
  ['SZA', 'Ctrl', 'The Weekend', 2017, 'r&b'],
  ['Lorde', 'Melodrama', 'Green Light', 2017, 'pop'],
  ['King Krule', 'The OOZ', 'Dum Surfer', 2017, 'rock'],
  ['Thundercat', 'Drunk', 'Them Changes', 2017, 'jazz'],
  ['Slowdive', 'Slowdive', 'Sugar for the Pill', 2017, 'rock'],
  ['Tyler, the Creator', 'Flower Boy', 'See You Again', 2017, 'hip-hop'],
  ['Vince Staples', 'Big Fish Theory', 'BagBak', 2017, 'hip-hop'],
  ['Sampha', 'Process', '(No One Knows Me) Like the Piano', 2017, 'r&b'],
  // 2018 — 10
  ['Mitski', 'Be the Cowboy', 'Nobody', 2018, 'indie'],
  ['Kacey Musgraves', 'Golden Hour', 'Slow Burn', 2018, 'folk'],
  ['Pusha T', 'Daytona', 'If You Know You Know', 2018, 'hip-hop'],
  ['Sons of Kemet', 'Your Queen Is a Reptile', 'My Queen Is Ada Eastman', 2018, 'jazz'],
  ['Jon Hopkins', 'Singularity', 'Emerald Rush', 2018, 'electronic'],
  ['Robyn', 'Honey', 'Missing U', 2018, 'pop'],
  ['Mac Miller', 'Swimming', 'Self Care', 2018, 'hip-hop'],
  ['Janelle Monáe', 'Dirty Computer', 'Make Me Feel', 2018, 'pop'],
  ['Kids See Ghosts', 'Kids See Ghosts', 'Reborn', 2018, 'hip-hop'],
  ['Low', 'Double Negative', 'Quorum', 2018, 'ambient'],
  // 2019 — 11
  ['Weyes Blood', 'Titanic Rising', 'Andromeda', 2019, 'indie'],
  ['FKA twigs', 'Magdalene', 'cellophane', 2019, 'r&b'],
  ['Tyler, the Creator', 'IGOR', 'EARFQUAKE', 2019, 'hip-hop'],
  ['Big Thief', 'Two Hands', 'Not', 2019, 'folk'],
  ['Floating Points', 'Crush', 'LesAlpx', 2019, 'electronic'],
  ['Angel Olsen', 'All Mirrors', 'Lark', 2019, 'indie'],
  ['Little Simz', 'GREY Area', 'Venom', 2019, 'hip-hop'],
  ['Michael Kiwanuka', 'KIWANUKA', 'You Ain’t the Problem', 2019, 'r&b'],
  ['Sharon Van Etten', 'Remind Me Tomorrow', 'Seventeen', 2019, 'rock'],
  ['Purple Mountains', 'Purple Mountains', 'All My Happiness Is Gone', 2019, 'folk'],
  ['Nick Cave & The Bad Seeds', 'Ghosteen', 'Bright Horses', 2019, 'rock'],
  // 2020 — 12
  ['Fiona Apple', 'Fetch the Bolt Cutters', 'Shameika', 2020, 'rock'],
  ['Phoebe Bridgers', 'Punisher', 'Kyoto', 2020, 'indie'],
  ['Perfume Genius', 'Set My Heart on Fire Immediately', 'On the Floor', 2020, 'pop'],
  ['Yves Tumor', 'Heaven to a Tortured Mind', 'Kerosene!', 2020, 'rock'],
  ['Run the Jewels', 'RTJ4', 'Ooh LA LA', 2020, 'hip-hop'],
  ['Waxahatchee', 'Saint Cloud', 'Lilacs', 2020, 'folk'],
  ['Moses Sumney', 'græ', 'Cut Me', 2020, 'r&b'],
  ['Adrianne Lenker', 'songs', 'anything', 2020, 'folk'],
  ['Jessie Ware', 'What’s Your Pleasure?', 'Spotlight', 2020, 'pop'],
  ['Dua Lipa', 'Future Nostalgia', 'Levitating', 2020, 'pop'],
  ['Charli xcx', 'how i’m feeling now', 'claws', 2020, 'pop'],
  ['Autechre', 'SIGN', 'M4 Lema', 2020, 'electronic'],
  // 2021 — 12
  ['Little Simz', 'Sometimes I Might Be Introvert', 'Introvert', 2021, 'hip-hop'],
  ['Japanese Breakfast', 'Jubilee', 'Be Sweet', 2021, 'indie'],
  ['Black Country, New Road', 'For the First Time', 'Sunglasses', 2021, 'rock'],
  ['Tirzah', 'Colourgrade', 'Tectonic', 2021, 'electronic'],
  ['Tyler, the Creator', 'Call Me If You Get Lost', 'WUSYANAME', 2021, 'hip-hop'],
  ['Olivia Rodrigo', 'SOUR', 'good 4 u', 2021, 'pop'],
  ['Jazmine Sullivan', 'Heaux Tales', 'Pick Up Your Feelings', 2021, 'r&b'],
  ['Snail Mail', 'Valentine', 'Valentine', 2021, 'indie'],
  ['Turnstile', 'Glow On', 'Blackout', 2021, 'rock'],
  ['The War on Drugs', 'I Don’t Live Here Anymore', 'Harmonia’s Dream', 2021, 'rock'],
  ['Lil Nas X', 'Montero', 'Montero (Call Me by Your Name)', 2021, 'pop'],
  ['Nala Sinephro', 'Space 1.8', 'Space 1', 2021, 'jazz'],
  // 2022 — 13
  ['Big Thief', 'Dragon New Warm Mountain I Believe in You', 'Simulation Swarm', 2022, 'folk'],
  ['Beyoncé', 'RENAISSANCE', 'CUFF IT', 2022, 'pop'],
  ['Alvvays', 'Blue Rev', 'Belinda Says', 2022, 'indie'],
  ['Kendrick Lamar', 'Mr. Morale & the Big Steppers', 'N95', 2022, 'hip-hop'],
  ['Sudan Archives', 'Natural Brown Prom Queen', 'Selfish Soul', 2022, 'r&b'],
  ['Makaya McCraven', 'In These Times', 'Seventh String', 2022, 'jazz'],
  ['Black Country, New Road', 'Ants From Up There', 'Chaos Space Marine', 2022, 'rock'],
  ['Rosalía', 'MOTOMAMI', 'SAOKO', 2022, 'pop'],
  ['SZA', 'SOS', 'Kill Bill', 2022, 'r&b'],
  ['Steve Lacy', 'Gemini Rights', 'Bad Habit', 2022, 'r&b'],
  ['The Smile', 'A Light for Attracting Attention', 'You Will Never Work in Television Again', 2022, 'rock'],
  ['Weyes Blood', 'And in the Darkness, Hearts Aglow', 'It’s Not Just Me, It’s Everybody', 2022, 'indie'],
  ['Danger Mouse & Black Thought', 'Cheat Codes', 'Sometimes', 2022, 'hip-hop'],
  // 2023 — 13
  ['Sufjan Stevens', 'Javelin', 'So You Are Tired', 2023, 'folk'],
  ['boygenius', 'the record', 'Not Strong Enough', 2023, 'indie'],
  ['Mitski', 'The Land Is Inhospitable and So Are We', 'My Love Mine All Mine', 2023, 'indie'],
  ['Lankum', 'False Lankum', 'Go Dig My Grave', 2023, 'folk'],
  ['Jessie Ware', 'That! Feels Good!', 'Free Yourself', 2023, 'pop'],
  ['Yves Tumor', 'Praise a Lord Who Chews but Which Does Not Consume', 'Echolalia', 2023, 'rock'],
  ['Caroline Polachek', 'Desire, I Want to Turn Into You', 'Welcome to My Island', 2023, 'pop'],
  ['Sampha', 'Lahai', 'Spirit 2.0', 2023, 'r&b'],
  ['Wednesday', 'Rat Saw God', 'Chosen to Deserve', 2023, 'rock'],
  ['Olivia Rodrigo', 'GUTS', 'vampire', 2023, 'pop'],
  ['Kelela', 'Raven', 'Contact', 2023, 'r&b'],
  ['ANOHNI and the Johnsons', 'My Back Was a Bridge for You to Cross', 'It Must Change', 2023, 'r&b'],
  ['Genesis Owusu', 'Struggler', 'Leaving The Light', 2023, 'hip-hop'],
  // 2024 — 12
  ['Charli xcx', 'BRAT', '360', 2024, 'pop'],
  ['Beyoncé', 'COWBOY CARTER', 'TEXAS HOLD ’EM', 2024, 'pop'],
  ['Vampire Weekend', 'Only God Was Above Us', 'Capricorn', 2024, 'indie'],
  ['MJ Lenderman', 'Manning Fireworks', 'She’s Leaving You', 2024, 'rock'],
  ['Nala Sinephro', 'Endlessness', 'Continuum 1', 2024, 'jazz'],
  ['Kendrick Lamar', 'GNX', 'squabble up', 2024, 'hip-hop'],
  ['Mk.gee', 'Two Star & the Dream Police', 'Are You Looking Up', 2024, 'r&b'],
  ['Waxahatchee', 'Tigers Blood', 'Right Back to It', 2024, 'folk'],
  ['Adrianne Lenker', 'Bright Future', 'Sadness As a Gift', 2024, 'folk'],
  ['Magdalena Bay', 'Imaginal Disk', 'Death & Romance', 2024, 'pop'],
  ['Fontaines D.C.', 'Romance', 'Starburster', 2024, 'rock'],
  ['Tyler, the Creator', 'CHROMAKOPIA', 'Noid', 2024, 'hip-hop'],
  // 2025 — 5, the present edge (kept sparse on purpose — the runway is still open)
  ['FKA twigs', 'EUSEXUA', 'Eusexua', 2025, 'pop'],
  ['Panda Bear', 'Sinister Grift', 'Praise', 2025, 'indie'],
  ['Mac Miller', 'Balloonerism', '5 Dollar Pony Rides', 2025, 'hip-hop'],
  ['Sharon Van Etten', 'Sharon Van Etten & the Attachment Theory', 'Afterlife', 2025, 'rock'],
  ['Bon Iver', 'SABLE, fABLE', 'Everything Is Peaceful Love', 2025, 'folk'],
];
